### ISSUE TITLE
listener.js crashes on a mac when accepting request

### ISSUE THREAD

**Issue by rajiprasanna** [Azure/azure-relay-node#18]
## Actual Behavior
The sample listener.js crashes with the following error on Mac OS X High Sierra while accepting Requests, but works fine on Windows.
/Users/raja/Documents/WebServer/relay/node_modules/hyco-https/lib/HybridConnectionHttpsServer.js:120
  COUNTER_HTTP_SERVER_RESPONSE();
  ^

ReferenceError: COUNTER_HTTP_SERVER_RESPONSE is not defined
    at ServerResponse._finish (/Users/raja/Documents/WebServer/relay/node_modules/hyco-https/lib/HybridConnectionHttpsServer.js:120:3)
    at ServerResponse.end (/Users/raja/Documents/WebServer/relay/node_modules/hyco-https/lib/_hyco_outgoing.js:665:10)
    at Server.https.createRelayedServer (/Users/raja/Documents/WebServer/relay/listener-old.js:21:13)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at WebSocket.<anonymous> (/Users/raja/Documents/WebServer/relay/node_modules/hyco-https/lib/HybridConnectionHttpsServer.js:593:17)
    at emitNone (events.js:106:13)
    at WebSocket.emit (events.js:208:7)
    at WebSocket.setSocket (/Users/raja/Documents/WebServer/relay/node_modules/ws/lib/websocket.js:151:10)
    at ClientRequest.req.on (/Users/raja/Documents/WebServer/relay/node_modules/ws/lib/websocket.js:602:10)
Rajas-Mac-Pro-1647:relay raja$ 

## Expected Behavior
1. 
2. 

## Versions  
- Mac OS X Hig Sierra
- Node Version: 8.11.3
- NPM package version or commit ID: 5.6.0

**Comment by clemensv** [comment]
Has been fixed in 1.1.0. Thank your for reporting.
