### ISSUE TITLE
hyco-https throws exeception on a POST request

### ISSUE THREAD

**Issue by rajiprasanna** [Azure/azure-relay-node#19]
## Actual Behavior
https post request throws following error

ReferenceError: server is not defined
    at requestChannelRequest (Z:\Documents\WebServer\relay\node_modules\hyco-https\lib\HybridConnectionHttpsServer.js:622:5)
    at WebSocket.requestChannel.onmessage (Z:\Documents\WebServer\relay\node_modules\hyco-https\lib\HybridConnectionHttpsServer.js:634:7)
    at WebSocket.onMessage (Z:\Documents\WebServer\relay\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (Z:\Documents\WebServer\relay\node_modules\ws\lib\websocket.js:720:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (Z:\Documents\WebServer\relay\node_modules\ws\lib\receiver.js:412:14)
    at Receiver.getData (Z:\Documents\WebServer\relay\node_modules\ws\lib\receiver.js:345:17)
## Expected Behavior
1. 
2. 

## Versions  
- Windows and Mac OS HighSierra
- Node Version: 8.11.3
- NPM package version or commit ID: 5.6.0

**Comment by clemensv** [comment]
Has been fixed in 1.1.0. Thank your for reporting.
