### ISSUE TITLE
ReferenceError: Extensions is not defined (hyco-https)

### ISSUE THREAD

**Issue by TamasKeul** [Azure/azure-relay-node#62]
## Actual Behavior
Sample script fails with the following error message upon incoming request:
The scripts connects to the relay service without problem.
```
C:\dev\test-azure-relay\node-relay\node_modules\hyco-https\examples\simple>node listener.js
C:\dev\test-azure-relay\node-relay\node_modules\hyco-https\lib\HybridConnectionHttpsServer.js:474
  var extensionsOffer = Extensions.parse(req.headers['sec-websocket-extensions']);
                        ^

ReferenceError: Extensions is not defined
    at accept (C:\dev\test-azure-relay\node-relay\node_modules\hyco-https\lib\HybridConnectionHttpsServer.js:474:25)
    at WebSocket.server.controlChannel.onmessage (C:\dev\test-azure-relay\node-relay\node_modules\hyco-https\lib\HybridConnectionHttpsServer.js:419:7)
    at WebSocket.onMessage (C:\dev\test-azure-relay\node-relay\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:400:28)
    at Receiver.receiverOnMessage (C:\dev\test-azure-relay\node-relay\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.dataMessage (C:\dev\test-azure-relay\node-relay\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (C:\dev\test-azure-relay\node-relay\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\dev\test-azure-relay\node-relay\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\dev\test-azure-relay\node-relay\node_modules\ws\lib\receiver.js:74:10)
```  

## Expected Behavior
The listener script should respond with the sample message written in sample listener:
```
res.end('<html><head><title>Hey!</title></head><body>Relayed Node.js Server!</body></html>');
```  

## Versions  
- OS platform and version: Windows 10, Docker Alpne, Docker Ubuntu 18.04
- Node Version: v14.18.1 , v10.24.1
- NPM package version or commit ID: hyco-https@1.4.5

**Comment by jbjordan** [comment]
Thank you for the information. There have been some recent dependency updates and I have confirmed the sample is working as expected. @TamasKeul Are you still experiencing this issue?
